### PR TITLE
Merge pr-template into master to create a PR Template for Widgets

### PR DESCRIPTION
**Pull request by RedFantom**
With this Pull Request, I would like to merge in a Pull Request Template with the preferred lay-out for a pull request containing a widget. This Template does not apply to other sorts of Pull Requests.

I think a template would be particularly useful because of the included checklist. With this checklist, incomplete branches can be easily identified.

### CODE REVIEW

**Comment by RedFantom** [comment]
That sounds like a good idea. Given how there is no real documentation for the package yet, perhaps requiring docstrings describing arguments would be appropriate?

Having proper documenation would of course be very helpful, but writing the documentation from the docstrings that all widgets currently have would be a pretty big task. Especially with new widgets still being added, and that existing widgets may be extended or modified in major ways while still under the `1.0.0` version number.

What do you think?

**Comment by j4321** [comment]
By documentation, what I really meant was docstrings. What I really like about Tkinter is that most widgets and methods have good enough docstrings so that I don't have to search the documentation to remember how to use them. That is what I would like to have in all widgets in ttkwidgets too. Then we can always write a proper documentation from the docstrings later, when we have time. There will be no hurry if the docstrings are descriptive enough.

I guess we could also have a template about widget improvement though I am not sure about what to put in it exactly.

**Comment by RedFantom** [comment]
Okay, in that case we were really thinking the same thing! I have added the docstring requirement to the checklist.

As for creating other templates, I wouldn't really know how to standardize such a thing at this time. We can always add more later if we see the need for it. The same applies for the issue template I created in the `issue-template` branch, I'm not quite happy with it yet.

Then I will merge this branch into master to activate the PR template.

**Comment by j4321** [comment]
I will take a look at the issue template then.

**Pull request merged**
