### PR TITLE
Merge autoscrollbar into master to add AutoHideScrollbar

### PR DESCRIPTION
**Pull request by j4321**
Add scrollbar that automatically hides when not needed. The idea comes from http://effbot.org/zone/tkinter-autoscrollbar.htm, but I have adapted it to all layouts.

### CODE REVIEW

**Comment by j4321** [comment]
We could also replace the scrollbars in `ScrolledListbox` and `ScrolledFrame` by autoscrollbars. What do you think?

**Comment by j4321** [comment]
@RedFantom As for the name, I have kept the same as in the code snippet from effbot.org, but if you have a suggestion, I don't mind changing it.

**Comment by RedFantom** [comment]
Personally, I'd say that `AutoHideScrollbar` would be a bit more descriptive about what it actually does, without being a lot longer.

**Comment by RedFantom** [comment]
Okay, then this is done. We should take a look at putting this into the Frames using a Scrollbar in a different PR, in my opinion.

**Pull request merged**
