### PR TITLE
Merge timeline into master to add TimeLine

### PR DESCRIPTION
**Pull request by RedFantom**
This widget provides an interactive TimeLine with categories, on which markers can be placed. Various options exist for changing the TimeLine's behaviour. Markers can be created with various options. All markers have three states (`normal`, `active` and `hover`).
timeline
The coverage for this widget is rather low, due to `left_motion` being based entirely on user interaction. Creating a test for this function would be hard to do, and it would be easy to break without the widget actually being broken.

For an elaborate description of the widget, please consult the docstring of the `TimeLine` class in the `timeline.py` widget.

### CODE REVIEW

**Comment by j4321** [comment]
I haven't looked at the code in details yet, but I have tried the example and I think the user experience would be smoother if the markers did not jump when you start dragging them because there left border goes to the mouse position.

Here are some code samples to show you what I mean:
_Jumpy behavior_
``` python
from tkinter import Canvas, Tk

root = Tk()
canvas = Canvas(root)
canvas.pack(fil='both', expand=True)
canvas.create_rectangle(1, 1, 71, 21, fill='red')
bind_id = ''

def motion(event, iid):
    x1, y1, x2, y2 = canvas.coords(iid)
    x, y = event.x, event.y 
    canvas.coords(iid, x, y, x + x2 - x1, y + y2 - y1)
    
def on_click(event):
    global bind_id
    x0, y0 = event.x, event.y
    items = canvas.find_overlapping(x0, y0, x0, y0)
    if items:
        bind_id = canvas.bind('<B1-Motion>', lambda event: motion(event, items[0]))

def on_release(event):
    global bind_id
    canvas.unbind('<B1-Motion>', bind_id)
    bind_id = ''

canvas.bind('<ButtonPress-1>', on_click)
canvas.bind('<ButtonRelease-1>', on_release)
root.mainloop()
```
_Smooth dragging_
``` python
from tkinter import Canvas, Tk

root = Tk()
canvas = Canvas(root)
canvas.pack(fil='both', expand=True)
canvas.create_rectangle(1, 1, 71, 21, fill='red')
bind_id = ''

def motion(event, iid):
    global x0, y0
    x, y = event.x, event.y 
    dx, dy = x - x0, y - y0
    x0, y0 = x, y
    canvas.move(iid, dx, dy)
    
def on_click(event):
    global bind_id, x0, y0
    x0, y0 = event.x, event.y
    items = canvas.find_overlapping(x0, y0, x0, y0)
    if items:
        iid = items[0]
        bind_id = canvas.bind('<B1-Motion>', lambda event: motion(event, iid))

def on_release(event):
    global bind_id
    canvas.unbind('<B1-Motion>', bind_id)
    bind_id = ''

canvas.bind('<ButtonPress-1>', on_click)
canvas.bind('<ButtonRelease-1>', on_release)

root.mainloop()
```
Basically, what I suggest is that the mouse remains at the same position with respect to the side of the item during the whole dragging. I know that the `left_motion` method is already very complicated because the overlapping checks and such, so this is just a suggestion.

**Comment by RedFantom** [comment]
That is a really great idea. I'll get to it as soon as I can.

**Comment by RedFantom** [comment]
I have implemented the smooth dragging on branch `timeline_smooth_dragging`, but it is interacting in a very annoying way with both the overlap protection and the snapping to ticks. What do you think?

**Comment by RedFantom** [comment]
@j4321 If you do not have sufficient time to provide reviews at this time, that's okay. I would still like to merge both this widget and the `ScaleEntry` widget though. Could you please let me know?

**Pull request merged**
