### PR TITLE
Fixed bug: check box of CheckboxTreeview can not show in Mac OS

### PR DESCRIPTION
**Pull request by jnhyperion**
Fixed bug: check box of CheckboxTreeview can not show in Mac OS

### CODE REVIEW

**Comment by RedFantom** [comment]
Thank you for opening a PR, @jnhyperion . Before I can merge this pull request, I need a bit more information about the issue that you are facing and that this pull request fixes. I see that you simply removed three image assets from the repository, but these image assets are required on other platforms, so could you explain what it accomplishes?

Also, could you make your commit message a bit more descriptive? I'd like for the commit message to be a proper summary of the fix.

**Comment by jnhyperion** [comment]
Hi @RedFantom ,

The issue is:

In CheckboxTreeview, the select box cannot show in Mac OS.

And I found out the root cause is these 3 images. So I edited the PNG files and replaced with the new one.

**Comment by j4321** [comment]
Hello @jnhyperion ,

Thanks for identifying this issue. Could you put a one pixel (or more) transparent border around the checkbox (either by shrinking the box or resizing the image's canvas to 15x15) so that the checkbox is not stuck to the text:
 - Current version of the CheckboxTreeview (in Linux):
    Capture d’écran_2019-07-22_08-43-06
- Your version:
   Capture d’écran_2019-07-22_08-42-48

**Comment by jnhyperion** [comment]
Hello @RedFantom
In order to prevent impacting the orginal check box style, I modified the pixel size from 19x14 (original) to 17x14. It works well in Mac OS.

**Comment by RedFantom** [comment]
This is how it looks like under Linux for me. Unfortunately, I cannot check Windows right now, and I won't be able to for at least two more weeks. The new one is on the left, the right one is the current version.
Screenshot from 2019-07-23 18-56-24
@jnhyperion : I think this is looking much better than the 19x4 versions. Would you mind waiting a bit so I can also see how it looks on Windows? Usually Treeviews look the same under Windows as under Linux, but I'd rather be sure. Of course, @j4321 has to agree as well that it looks okay.

**Comment by jnhyperion** [comment]
@RedFantom It's OK.

**Comment by j4321** [comment]
@RedFantom , @jnhyperion I am ok with how it looks now in Linux (I cannot check in Windows at the moment either).

**Comment by evotodi** [comment]
I can confirm the look on Windows 10 Py3.7 / Mac 10 Py3.6
Screen Shot 2019-07-24 at 8 01 44 AM
ttkwidgets-windows

**Comment by RedFantom** [comment]
@evotodi Thank you for checking whether it looks okay on Windows and for confirming that you are also affected by the issue! As @j4321 is okay with how the changes look, I will merge these into the master branch. Thanks, @jnhyperion!

**Pull request merged**
